# Generated by Django 5.2.4 on 2025-08-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstatus',
            unique_together=set(),
        ),
    ]
