# Generated by Django 5.2.4 on 2025-08-14 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_passwordresettoken_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalation',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Escalations'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ['-status_date'], 'verbose_name': 'Project Status', 'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique project code, e.g. 1000000002-01S', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Code must match the pattern 100000000<number>-01S, e.g. 1000000002-01S', regex='^100000000\\d+-01S$')]),
        ),
    ]
